plugins {
  id "com.android.application"
}

android {
  namespace "io.qzz.superstar1014.mynotes"
  compileSdk 36

  defaultConfig {
    applicationId "io.qzz.superstar1014.mynotes"
    minSdk 36
    targetSdk 36
    versionCode 30
    versionName "2.19"
    testInstrumentationRunner "io.qzz.superstar1014.mynotes.CryptoTestRunner"
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

dependencies {
  implementation "com.squareup.okhttp3:okhttp:5.4.0"
}

tasks.withType(JavaCompile).configureEach {
  options.compilerArgs += ["-Xlint:deprecation"]
}
